-- --------------------------------------------------------
-- Host:                         127.0.0.1
-- Versión del servidor:         8.0.30 - MySQL Community Server - GPL
-- SO del servidor:              Win64
-- HeidiSQL Versión:             12.1.0.6537
-- --------------------------------------------------------

/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET NAMES utf8 */;
/*!50503 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


-- Volcando estructura de base de datos para peaku
CREATE DATABASE IF NOT EXISTS `peaku` /*!40100 DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci */ /*!80016 DEFAULT ENCRYPTION='N' */;
USE `peaku`;

-- Volcando estructura para tabla peaku.blogs
CREATE TABLE IF NOT EXISTS `blogs` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `content` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `autor` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `images` text COLLATE utf8mb4_unicode_ci,
  `datepublish` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT '',
  `datecreate` datetime DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=10 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Volcando datos para la tabla peaku.blogs: ~9 rows (aproximadamente)
DELETE FROM `blogs`;
INSERT INTO `blogs` (`id`, `name`, `content`, `autor`, `images`, `datepublish`, `datecreate`) VALUES
	(1, 'The Amazing Difference a Year of Travelling.', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Lorem Ipsum', '/images/blogs/blog01.png', 'July 27, 2021', '2024-03-12 17:27:42'),
	(2, 'Exploring Hidden Gems: A Journey Through Enchanted Forests', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Alice Adventure', '/images/blogs/blog02.png', '2021-08-10', '2024-03-12 23:15:18'),
	(3, 'Capturing Sunsets: A Photographer\'s Tale', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Shutterbug Sam', '/images/blogs/blog03.png', '2021-09-05', '2024-03-13 10:42:30'),
	(4, 'Culinary Adventures: Tasting the World One Dish at a Time', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Gastronomy Guru', '/images/blogs/blog04.png', '2021-10-20', '2024-03-14 08:03:55'),
	(5, 'Starry Nights: Camping Under the Milky Way', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Night Sky Nomad', '/images/blogs/blog05.png', '2021-11-15', '2024-03-15 19:58:12'),
	(6, 'The Enchanted Valley: A Tale of Mystical Creatures', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Evelyn Enigma', '/images/blogs/blog06.png', '2021-12-05', '2024-03-16 14:20:07'),
	(7, 'Lost in Time: Unraveling Ancient Secrets', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Archaeologist Alex', '/images/blogs/blog07.png', '2022-01-18', '2024-03-17 09:45:33'),
	(8, 'Whispers of the Wind: Haunting Legends from the Highlands', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Storyteller Sylvia', '/images/blogs/blog08.png', '2022-02-28', '2024-03-18 18:12:59'),
	(9, 'Cosmic Wanderlust: Journeying Beyond Our Solar System', 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Duis nec tellus a ante faucibus ullamcorper sed vel nibh. Aliquam non tortor non urna ornare tristique dignissim ut augue. Aliquam urna ex, ultricies ut gravida sed, rutrum ac turpis. Curabitur a enim eleifend, tristique turpis eu, interdum neque. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Ut aliquam malesuada ex, quis semper nisl mattis a. Proin quis mi ac dolor malesuada scelerisque. In laoreet augue purus, fringilla lobortis nibh malesuada id. Donec quis quam laoreet, sagittis ex vitae, venenatis velit. Maecenas aliquam nibh vel ipsum rutrum, vitae auctor mi faucibus. In interdum est non diam pellentesque, a malesuada enim ultricies. Ut vitae elit ex. Aliquam feugiat nunc id turpis mollis porttitor.', 'Stellar Voyager', '/images/blogs/blog09.png', '2022-03-22', '2024-03-19 23:59:01');

/*!40103 SET TIME_ZONE=IFNULL(@OLD_TIME_ZONE, 'system') */;
/*!40101 SET SQL_MODE=IFNULL(@OLD_SQL_MODE, '') */;
/*!40014 SET FOREIGN_KEY_CHECKS=IFNULL(@OLD_FOREIGN_KEY_CHECKS, 1) */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40111 SET SQL_NOTES=IFNULL(@OLD_SQL_NOTES, 1) */;
